### ISSUE TITLE
Cross-modal retrieval

### ISSUE THREAD

**Issue by Null-0000** [hssip/FashionSAP#3]
请问在cross-modal retrieval下游任务中text2img的指标较低可能是什么原因导致的？
![图片](https://user-images.githubusercontent.com/54805967/236668218-420118de-2e5a-447a-b122-722df508d201.png)

**Comment by hssip** [comment]
感谢对我们项目和代码的关注，我们已经在最近的commit中修复了代码中存在的bug。

**Comment by Null-0000** [comment]
感谢
